### ISSUE TITLE
Make Triggering Process Details Available To Actions

### ISSUE THREAD

**Issue by kevin-montrose** [dotnet/dotnet-monitor#3606] opened 2023-02-08 18:30 UTC
## Background and Motivation

This (and [another issue](https://github.com/dotnet/dotnet-monitor/issues/3605)) came out of investigation for replacing some bespoke monitoring code with dotnet-monitor.  It's possible I missed some way to accomplish this that already exists.

We have a ton of processes we're monitoring, a number of which are spun up by ServiceFabric (or similar automated services), so our CollectionRules are numerous and relatively broad (just name matches).  We also have a number of tools which we want to run via Actions which need a PID or other details.

While we could probably hack something together with exact name matches or bespoke tools, ideally `dotnet-monitor` would make the details of the process (if any) triggering a CollectionRule available.

## Proposed Feature

The exact names don't matter, but make something like `$(Trigger.Process.Id)`, `$(Trigger.Process.Name)`, and so on available in Actions.

Ideally everything allowed for Filters would be passed, if available, so PID, Name, and CommandLine.

## Usage Examples

One of our collection rules would look something like:
```
{ 
  "AutomatedAnalysis": { 
    "Filters": [ 
        { 
            "Key": "ProcessName", 
            "Value": "Our.Unique.Namespace", 
            "MatchType": "Contains" 
        } 
    ], 
    "Trigger": { 
        "Type": "GCHeapSize", 
        "Settings": { 
            "GreaterThan": 15000, 
            "SlidingWindowDuration": "00:00:05" 
        } 
    }, 
    "Actions": [ 
        { 
            "Name": "Analyze", 
            "Type": "Execute", 
            "Settings": { 
                "Path": "<path to analysis exe>", 
                "Arguments": "-FocusProcessId \"$(Trigger.Process.Id)\" -ReportName \"$(Trigger.Process.Name)-$(Trigger.Process.Id).report\" 
            }, 
            "WaitForCompletion": true 
        }
    ]
}
```

**Comment by jander-msft** [comment] 2023-02-09 08:24
Duplicate of #893, but better explanation of the usage.

**Comment by jander-msft** [comment] 2023-03-23 23:36
These were added in 7.1 and 8.0 Preview 2 earlier this month. See https://github.com/dotnet/dotnet-monitor/blob/main/documentation/collectionrules/collectionrules.md#additional-token-substitution for documentation.

**Closed by jander-msft** 2023-03-23 23:36 UTC
Labels: enhancement
